### ISSUE TITLE
'CocoaLumberjack/CocoaLumberjack.h' file not found

### ISSUE THREAD

**Issue by tseven** [mistak1992/MKCooling#1]
While trying to compile with Xcode 12.3 I am getting the following error:
`CocoaLumberjack/CocoaLumberjack.h' file not found`

Line 17 of PrefixHeader.pch

**Comment by mistak1992** [comment]
This project use carthage as package manager.
You should install carthage by eg.
```
brew install carthage
```
then
```
carthage update --platform macOS
```
finally
retry to build this project
(been tested in Xcode 12.3, it works fine)
